version: '3.8'

services:
  echo:
    build:
      context: .
      dockerfile: ./docker/DockerFile
    volumes:
      - ./:/echo
    stdin_open: true
    tty: true
    # Increase shared memory size to avoid 'bus error' in data-intensive tasks
    # ex: using multiple workers for dataloader. Increase accordingly
    shm_size: '2gb'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
