version: '3.8'

services:
  echo:
    build:
      context: .
      dockerfile: ./docker/DockerFile
    volumes:
      - ./:/echo
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
