version: '3.8'

services:
  echo:
    build:
      context: .
      dockerfile: ./docker/DockerFile
    volumes:
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
