FROM nvidia/cuda:12.3.1-devel-ubuntu22.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
    software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y \
    git \
    # Install Python 3.11
    python3.11 \
    python3.11-distutils \
    python3-pip && \
    # Set Python 3.11 as the default
    update-alternatives --install /usr/bin/python python /usr/bin/python3.11 1 && \
    # Cleaning up cache to reduce layer size
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Update pip to the latest version
RUN python -m pip install --upgrade pip

# Install Poetry
RUN pip install poetry

# set the working directory
WORKDIR /app

# copy the dependencies file to the working directory
COPY poetry.lock pyproject.toml ./

# Install project dependencies
RUN poetry install --without dev

# Copy the rest of the project
COPY . ./

# Set the entrypoint
ENTRYPOINT [ "/bin/bash" ]
